---
# tasks file for apigee-opdk-monitoring-grafana-config
- name: Update grafana attributes
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'grafana_response_file', value: "{{ opdk_installer_path }}/apigee-dashboard-response-grafana.conf" }
  - { key: 'influxdb_ip', value: "{{ hostvars[groups['influxdb'][0]][interface_name].ipv4.address }}" }
  - { key: 'influxdb_port', value: "{{ influxdb_port }}" }

- name: Create telegraph response file
  template:
    src: apigee-dashboard-response-grafana.conf.j2
    dest: "{{ grafana_response_file }}"


